# Generated by Django 3.1.1 on 2024-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_detail', '0002_podcast_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='body',
            field=models.CharField(blank=True, default=models.CharField(max_length=100), max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, default='img_5.jpg', null=True, upload_to='media'),
        ),
    ]
