# Generated by Django 3.1.1 on 2024-03-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_detail', '0003_auto_20240324_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='body',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
