# Generated by Django 3.1.1 on 2024-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_detail', '0004_auto_20240324_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
