# Generated by Django 3.1.1 on 2024-03-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactme',
        ),
    ]
