# Generated by Django 5.2.4 on 2025-07-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20240323_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
